# Usage: Follow the steps in the README file in the directory containing this file
version: "3"
services:
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
            - "17001:17001"
            - "18001:18001"
            - "8888:8888"
        volumes:
            - ..:/workspaces/opencog-central
            - ${HOME:-~}/.gitconfig:/home/opencog/.gitconfig # for git commits,stash ...
            - ${HOME:-~}/.ccache:/home/opencog/.ccache # for persisting ccache artifacts
        environment:
            - OPENCOG_SOURCE_DIR=/workspaces/opencog-central
            - CCACHE_DIR=/home/opencog/.ccache
            - PGHOST=db # This should be the same as the link's alias
            - PGUSER=opencog_user # user created by configure-database.sh
            - TZ=${TZ:-UTC} # set this to your timezone or default to UTC
            - ATOMSPACE_SOURCE_DIR=/workspaces/opencog-central/atomspace
            - COGUTIL_SOURCE_DIR=/workspaces/opencog-central/cogutil
        links:
            - postgres:db
            - relex:relex

    postgres:
        image: singularitynet/postgres
        # Uncomment the following lines if you want to work on a production
        # system.
        # NOTE: The environment variable `PROD` is set `True` then the entrypoint
        # script in opencog/postgres does additional configurations.
        # environment:
        #     - PROD=True

    relex:
        image: singularitynet/relex
        command: /bin/sh -c "./opencog-server.sh"
